version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.2
    container_name: elasticsearch
    environment:
      - node.name=esNode1
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=qz9E3VWsJX1vE5bp54Bp
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      #- 9300:9300
