apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.2
    generation: null
    importPolicy: {}
    name: 6.2.2
status:
  dockerImageRepository: ""
